type_ = {
    'String': 'varchar',
    'string': 'varchar',
    'Timestamp': 'date',
    'timestamp': 'date',
    'Integer': 'int',
    'integer': 'int',
    'int': 'int',
    'bigint': 'big_int',
    'Bigint': 'big_int',
    'Long': 'big_int',
    'long': 'big_int',
    'Boolean': 'bool',
    'boolean': 'bool',
    'BOOL': 'bool',
    'Bool': 'bool',
    'Double': 'double',
    'double': 'double',
    'float': 'numeric',
    'Float': 'numeric',
    'FLOAT': 'numeric',
}
